### PR TITLE
Adding Frameworks and perms for them

### PR DESCRIPTION
**Pull request by ghost**
Allow Frameworks and perms. 

Standalone with natives and add admins from folder server then main.lua then line 12. Can check discord, ip, steamid and license, 

Everybody just allows open without any perm checks, 

ESX check perms from ESX.getGroup() with esx legacy tested everything can be updated if anything needed.

### CODE REVIEW

**Comment by DoluTattoo** [comment]
I wont add support for ESX or any other framework because this is a devtool, it has nothing to do in prod environment...
The config function Im providing let people add their own server callback to check for permission.
+ Looks like you duplicated some files to the root folder..?
+ Why asking for framework in config since you can just detect it automaticly with `GetResourceState()`

**Comment by DoluTattoo** [comment]
Wait what, I saw that you added server callbacks in each functions?
This will destroy people's servers man

**Comment by ghost** [comment]
Hello Dolutatto, anwser to you questions

1.  GetResourceState(). Yes this could be done but even if you have one of the resources needed from a framwork you may still want other perm system depending on what you are doing.
2. i see  what you mean  i actually dont know why it did like that. i could update but as you state the update as unneeded i might not need to.
3. i dont really see destroy servers as it being called in commands once and not in any threads. what ever framwork you use in the config will only be trigger inside that command but yes i could make it better it was 5 min fix for me to be able to use it on a roleplay server and not that everyone can access it. If you want frameworks i dont mind to fix any preformance problem that you feel are a problem with my fork update from your main. 
4. the idea of the framwork is that i help servers with problems they have and this is a good tool to use for some of the information and test i need to do sometimes and the framworks was for me to be able to just add it to a server change Config.framework and go in and test what i need without having to have other versions

Best regards Andiystyler

**Comment by DoluTattoo** [comment]
Making proper permission system for this resource needs way more refactor.
Duplicating this server callback everywhere is absolutely not possible since it makes the code impossible to read and some functions (existing or future ones) will probably spam the server.
This tool was not made (and again, has nothing to do) for prod environments.

If devs want to work with it, just run it locally but it is not the role of admins/players to use it

**Comment by ghost** [comment]
Hello Dolutatto, Yes i agree it is made to be used locally.

We can close this pr

Best regards Andiystyler

**Pull request closed without merging**
